### ISSUE TITLE
Change bootstrap props so app so it looks 'better' in a mobile browser.

### ISSUE THREAD

**Issue by tomdieli** [tomdieli/fistfight#1]
Should show single columns(for the most part) if using a phone in portrait orientation.

**Comment by Forever0knight** [comment]
Hey i would like to contribute in your project, would be nice if you added a readme for better understanding of project.

**Comment by Forever0knight** [comment]
I couldn't figure out how to run the code, some additional information might help me.
I used
''' python manage.py runserver '''
but it didn't work

**Comment by tomdieli** [comment]
hello Forever0Knight, and thank you for your interest in fistfight! You are correct that a readme would be very helpful. i will get on that... 

this is a flask app. my initial inspiration was 'the simplest online multiplayer game that would work'. i ended up using a few flask plugins in the back as well as bootstrap and socket.io for the front.

and yes, launching the app is a bit different than a generic flask app. for dev purposes, i generally use the command

python arena_dev.py

keep in mind you will need to set REDIS_URL and DATABASE_URL in your environment. this will require you to have a postgres and redis server instance.

**Comment by tomdieli** [comment]
changed the dev('main') branch config to allow LAN access. Added the viewport meta tag which has improved phone portrait appearance. Unfortunately, getting kicked back to login page after login, not to the lobby. Is broke.

**Comment by tomdieli** [comment]
made some minor changes so that the app is functional. it does look better in my phone browser so....fixed!
